const fs = require('node:fs');
let content = fs.readFileSync('.env.example', 'utf8');
content = content.replace(/REDIS_URL=\".*\"/, 'REDIS_URL=\"redis://localhost:6379\"');
content = content.replace(/DATABASE_URL=\'.*\'/, 'DATABASE_URL=\"postgresql://user:password@localhost:5432/dbname\"');
content = content.replace(/DATABASE_URL_DIRECT=\'.*\'/, 'DATABASE_URL_DIRECT=\"postgresql://user:password@localhost:5432/dbname\"');
content = content.replace(/JWT_SECRET=\".*\"/, 'JWT_SECRET=\"your_super_secret_jwt_key\"');
content = content.replace(/SMTP_PASS=\".*\"/, 'SMTP_PASS=\"your_smtp_password\"');
content = content.replace(/R2_SECRET_ACCESS_KEY=\".*\"/, 'R2_SECRET_ACCESS_KEY=\"your_r2_secret\"');
content = content.replace(/R2_ACCESS_KEY_ID=\".*\"/, 'R2_ACCESS_KEY_ID=\"your_r2_key\"');
content = content.replace(/R2_ACCOUNT_ID=\".*\"/, 'R2_ACCOUNT_ID=\"your_r2_account_id\"');
content = content.replace(/R2_SECRET_ACCESS_KEY_2=\".*\"/, 'R2_SECRET_ACCESS_KEY_2=\"your_r2_secret_2\"');
content = content.replace(/R2_ACCESS_KEY_ID_2=\".*\"/, 'R2_ACCESS_KEY_ID_2=\"your_r2_key_2\"');
content = content.replace(/R2_ACCOUNT_ID_2=\".*\"/, 'R2_ACCOUNT_ID_2=\"your_r2_account_id_2\"');
content = content.replace(/LOUVIN_API_KEY=.*/, 'LOUVIN_API_KEY=your_louvin_api_key');
fs.writeFileSync('.env.example', content);
